import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar structure for our textbook
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro', 'intro-demo'],
    },
    {
      type: 'category',
      label: 'Chapters',
      items: [
        'chapters/ch01-introduction-to-physical-ai',
        'chapters/ch02-locomotion-systems',
        'chapters/ch03-perception-systems',
        'chapters/ch04-gazebo-simulation-basics',
        'chapters/ch05-unity-for-human-robot-interaction',
        'chapters/ch06-robot-manipulation-and-control',
        'chapters/ch07-perception-and-computer-vision-for-robotics',
        'chapters/ch08-path-planning-and-navigation',
        'chapters/ch09-mobile-robot-platforms-and-hardware-integration',
        'chapters/ch10-robot-operating-system-ros-architecture',
        'chapters/ch11-control-systems-for-robotics',
        'chapters/ch12-human-robot-interaction-principles',
        'chapters/ch13-robot-learning-and-adaptation',
        'chapters/ch14-multi-robot-systems-and-coordination',
        'chapters/ch15-safety-and-ethics-in-robotics',
        'chapters/ch16-future-trends-in-physical-ai-and-robotics',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'tutorials/rag-chatbot-integration-plan',
        'tutorials/chatbot-component-implementation',
      ],
    },
    {
      type: 'category',
      label: 'Exercises',
      items: [
        'exercises/chapter-01-exercises',
        'exercises/chapter-02-exercises',
        'exercises/chapter-03-exercises',
      ],
    },
  ],
};

export default sidebars;
